services:
  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: ecommerce-otel-collector
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    volumes:
      - ./observability/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo
  tempo:
    image: grafana/tempo:latest
    container_name: ecommerce-tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./observability/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
  grafana:
    image: grafana/grafana:latest
    container_name: ecommerce-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - tempo

volumes:
  postgres_data:
  redis_data:
  tempo_data:
  grafana_data:
